- lib/docurium.rb
- site/index.html
- site/js/docurium.js
+ Running 0.4.2 on Ubuntu 14.04 LTS I got encoding errors with html codes, e.g. `&alpha;`. I didn't manage to escape those by changing my settings. However, forcing the encoding to utf8 in docorium.rb, as discussed [here](http://stackoverflow.com/questions/11091879/handling-bad-utf-8-from-json-in-ruby) solved the problem.
+ Functions returning an enum were not reported in the `Returned by` field of the corresponding enum page, because exact matching was not allowed. The corresponding regexp was changed.
+ A callback entry has been added as a submenu of `Types`, in the sidebar. Furthermore if a menu or submenu is empty it is no more reported on the sidebar.
+ In addition to functions, callbacks are also reported as `Argument in` or `Returned by` for enums and structs.
+ The `Returned by` …
> Some tweaks and more love for callbacks

- Gemfile
- bin/cm
- docurium.gemspec
- lib/docurium.rb
- lib/docurium/cli.rb
- lib/docurium/docparser.rb
- test/docurium_test.rb
- test/gen_test.rb
- test/parser_test.rb
These are a few of the updates in #26 since it's too big to review or accept in a single run. This is mostly around updating dependencies and making it easier to check the changes against the repository itself.
/cc @tiennou
> Update dependencies and  add options to limit what to generate

- .travis.yml
- docurium.gemspec
- test/docurium_test.rb
- test/fixtures/git2/common.h
- test/parser_test.rb
Use Ubuntu Xenial and LLVM 6 since that what we'll end up using to generate the docs.
This includes messing around with `size_t` which for some reason makes it think that nothing has docs.
> Update dependencies in Travis to something current

- lib/docurium.rb
- test/docurium_test.rb
- test/fixtures/git2/cherrypick.h
Functions like `git_cherrypick` should be in the `cherrypick` group even though it doesn't have a third level of namespacing.
> Allow functions with just two namespace levels

- test/fixtures/git2/cherrypick.h
It seems the missing `#endif` guard displeases Apple's clang.
> Add missing #endif guard

- test/fixtures/git2/types.h
This makes GIT_BEGIN/END_DECL visible to clang.
> Add a missing include

- lib/docurium.rb
This avoids the warnings of a missing options instance variable. Presumably this
is because we passed in the class instead of a new instance of it.
This should be a less intrusive and workaroundy version of the silencing in #40
> Initialise the HTML renderer options

- lib/docurium.rb
- lib/docurium/docparser.rb
- lib/docurium/layout.rb
- test/docurium_test.rb
We have a few warnings. Fix them.
> Fix warnings

- lib/docurium.rb
- lib/docurium/docparser.rb
- site/css/style.css
- site/index.html
- site/js/docurium.js
- test/docurium_test.rb
- test/fixtures/git2/repository.h
This contains changes to the web UI when displaying structs.
> Restyle structs

- .travis.yml
- lib/docurium/docparser.rb
- test/fixtures/git2/common.h
For quite a while we've had the issue that some type definitions were missing, most notably `size_t` when generating documentation for libgit2. We "solved" that by defining it ourselves when `DOCURIUM` is defined. This is clearly a terrible hack but we did not know what was happening.
Then in #39 we got errors about not finding `stddef.h`. Further investigation revealed that this was because that PR included a change to ask the library to print out errors.
It turns out that by default we do not include the directory in which clang stores its headers, which means we've been missing some necessary ones for quite some time now.
This PR queries clang for its include file by parsing its verbose output (inspiration from drothlis/clang-ctags#7) and passing it as an include path. We also remove …
> Use clang's include paths when parsing the translation units

- lib/docurium/docparser.rb
This adds a fallback for the `$PATH`-installed `clang` executable, which sidesteps `llvm-config` not being provided on macOS. This also relaxes the regex, as the required SDK headers on macOS have strange paths.
> Use the locally installed clang, and make it work on macOS

- bin/cm
- lib/docurium.rb
- lib/docurium/cli.rb
(extracted from #26, based on #34)
This adds a warning on missing documentation comments on globals.
> Warn on undocumented globals

- lib/docurium.rb
- lib/docurium/docparser.rb
- test/parser_test.rb
This updates how we interface with clang so we get better reporting, limited to one error (which is usually a bad sign), the possibility to pass custom compile flags (I need to point clang 7.0 to my SDKs headers), as well as some slight filesystem optimizations.
> docparser cleanups

- bin/cm
- lib/docurium.rb
- lib/docurium/cli.rb
- lib/docurium/debug.rb
- lib/docurium/docparser.rb
- test/docurium_test.rb
This adds a quick debugging interface, so it's easier to grasp what's actually going wrong while processing cursors. Arguably, my other PRs that need arguments only depend on https://github.com/libgit2/docurium/commit/a17c1512a6977a889a92779c8830b560f09f8762, so if the debugging is too much, I can fold. But to be frank, it has been a great help already in pinpointing types that fail to document properly.
Extracted from #26, depends on #39.
> Add debugging helpers

- docurium.gemspec
- lib/docurium.rb
#26 originally removed all traces of parallelism in favor of less file-descriptor contention. It turns out Ruby has gems, and some of those provide ready-made, easy-to-use wrappers for parallel processing.
Use https://github.com/grosser/parallel instead of rolling our own, or removing parallelization altogether.
(Note that this is based on #39, for historic reasons. I can rebase that on top of master if it makes it easier to go in).
> Switch to parallel gem

- site/js/docurium.js
Links to github files with multiple lines are not in the right format.
Should be according to: https://help.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet
> Fix multiline github links

- lib/docurium.rb
If the 'user.name' and 'user.email' are not configured, the commit of
the generated documentation fail.
In this case, the options ['author'] and ['committer'] argument of the
Rugged::Commit.create(..), contain a nil content but a string was
expected.
> Add clean exit if no git user configuration is set

- docurium.gemspec
Some updates to the gems we use. Of particular interest is the fact that the `rubysl` stuff around rubinious makes bundle try to install it and as it requires ruby 2, we cannot fulfill that on 3 and thus fail. This should let the Travis job that tests against ruby head work again.
> Update gems, let CI work with ruby 3

- .github/workflows/main.yml
This is the library/tool we use for doing text highlighting and in its absence
we end up calling out to the network which isn't great for CI.
> ci: install python-pygments

- lib/docurium.rb
- site/index.html
- site/js/docurium.js
- test/docurium_test.rb
This PR improves type hotlinking by making sure we look for type usage in struct fields, as well as a quick fix for the regex that JS uses to hotlink types. This was triggered by missing `git_oid` links in the current libgit2 API.
> Link more types in the documentation
